version: "3"
services:
  front:
    build:
      context: ./spotipie
      dockerfile: Dockerfile
    ports:
      - 1420:1420
    depends_on:
      - backend
  backend:
    build:
      context: ./spotipieBack
      dockerfile: Dockerfile
    ports:
      - 8080:8080
